(function(){
	'use strict';
	
	// Source - https://en.wikipedia.org/wiki/List_of_indigenous_language_names
	var terms = ['Abaza', 'Abenaki', 'Abkhaz', 'Adyghe', 'Afar', 'Afrikaans', 'Ainu', 'Akan', 'Albanian', 'Aleut', 'Amharic', 'Apache', 'Arabic', 'Aragonese', 'Aramaic', 'Arapaho', 'Armenian', 'Armenian (Eastern)', 'Armenian (Western)', 'Arrernte', 'Assamese', 'Asturian', 'Avar', 'Aymara', 'Azerbaijani', 'Balinese', 'Basque', 'Bassa', 'Belarusian', 'Bemba', 'Bengali', 'Bhojpuri', 'Blackfoot', 'Borama Script', 'Bosnian', 'Breton', 'Buginese', 'Bulgarian', 'Braille', 'Buhid', 'Burmese', 'Cantonese', 'Carrier', 'Catalan', 'Cayuga', 'Cebuano', 'Chamorro', 'Chechen', 'Cherokee', 'Cheyenne', 'Chichewa', 'Chickasaw', 'Chinese', 'Chinese (Classical)', 'Chipewyan', 'Choctaw', 'Cimbrian', 'Circassian', 'Comanche', 'Coptic', 'Cornish', 'Corsican', 'Cree', 'Creek', 'Croatian', 'Cypriot', 'Czech', 'Dakota', 'Dalecarlian', 'Dangme', 'Danish', 'Dargwa', 'Dari', 'Deseret alphabet', 'Dungan', 'Dutch', 'Dzongkha', 'Egyptian Hieroglyphic Language', 'English', 'Erzya', 'Esperanto', 'Estonian', 'Ewe', 'Eyak', 'Faroese', 'Fijian', 'Fiji Hindi', 'Finnish', 'Fon', 'French', 'Frisian (North)', 'Frisian (Saterland)', 'Friulian', 'Ga', 'Galician', 'Gan', 'Ganda', 'Ge\'ez', 'Georgian', 'German', 'Gilbertese', 'Godoberi', 'Gothic', 'Greek', 'Greenlandic', 'Guarani', 'Gujarati', 'Gwich\'in', 'Haida', 'Haitian Creole', 'Hakka', 'Harari', 'Hausa', 'Hawaiian', 'Hebrew', 'Herero', 'Himba', 'Hindi', 'Hungarian', 'Icelandic', 'Ido', 'Igbo', 'Ilocano', 'Indonesian', 'Ingush', 'Interlingua', 'Inuktitut', 'Iñupiaq', 'Irish', 'Italian', 'Javanese', 'Japanese', 'Jersey Norman', 'Judaeo-Spanish', 'Jutish', 'Kabardian', 'Kabyle', 'Kaingang', 'Kannada', 'Kanuri', 'Karakalpak', 'Karelian', 'Kashmiri', 'Kashubian', 'Kazakh', 'Khakas', 'Khmer', 'Kiribati', 'Konkani', 'Korean', 'Kumyk', 'Kurdish', 'Kwanyama', 'Ladin', 'Lakota', 'Lao', 'Latin language', 'Latvian', 'Laz', 'Leonese', 'Limburgish', 'Lingala', 'Lithuanian', 'Livonian', 'Low German', 'Luo', 'Luri', 'Luxembourgish', 'Macedonian', 'Malay', 'Malayalam', 'Maltese', 'Manchu', 'Mandarin', 'Manx', 'Māori', 'Marathi', 'Maasai', 'Mongolian', 'Nama', 'Navajo', 'Nepali', 'Norwegian', 'Occitan', 'Ojibwe', 'Old English', 'Persian', 'Phoenician', 'Pitjantjatjara', 'Plautdietsch', 'Polish', 'Portuguese', 'Punjabi language', 'Romanian', 'Romansh', 'Runic', 'Russian', 'Samoan', 'Sanskrit', 'Sardinian', 'Scots', 'Scottish Gaelic', 'Serbian', 'Shanghaiese', 'Shona', 'Sichuan Yi', 'Sicilian', 'Sinhala', 'Slovak', 'Slovene', 'Somali', 'Sotho', 'Spanish', 'Sundanese', 'Stellingwarfs', 'Swahili', 'Swedish', 'Swiss German', 'Tahitian', 'Tamil', 'Tatar', 'Telugu', 'Teochew', 'Teribe', 'Tetum', 'Thai', 'Tibetan', 'Tigrinya', 'Tok Pisin', 'Tongan', 'Tsez', 'Tswana', 'Turkish', 'Tulu language', 'Ukrainian', 'Urdu', 'Uyghur', 'Uzbek', 'Venda', 'Venetian', 'Vietnamese', 'Volapük', 'Võro', 'Walloon', 'Warlpiri', 'Welsh', 'West Frisian', 'Wolof', 'Wu', 'Xhosa', 'Xiang', 'Yapese', 'Yiddish', 'Yoruba', 'Zhuang', 'Zulu'];

	var myAutocomplete = new Autocomplete(terms),
		inputElem = document.getElementById('input'),
		resultsElem = document.getElementById('results');

	myAutocomplete.bindResults(inputElem, resultsElem);

}());